# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.123.0
    hooks:
      - id: renovate-config-validator