services:
  workflow:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/sirius-workflow:latest
    build:
      dockerfile: docker/sirius-workflow/Dockerfile
    ports: [ "8888:8888" ]
    privileged: false
    user: app
    environment:
      PORT: 8888
      HEALTHCHECK: "/supervision/workflow/health-check"
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      SHOW_BONDS_WITHOUT_ORDERS: 1
    depends_on:
      - json-server

  json-server:
    build:
      dockerfile: docker/json-server/Dockerfile
    ports:
      - '3000:3000'

  test-runner:
    build:
      dockerfile: docker/test-runner/Dockerfile
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app

  cypress:
    build:
      dockerfile: docker/cypress/Dockerfile
    command: [ "--headless", "-b", "electron", "--env", "grepUntagged=true" ]
    volumes:
      - ./cypress/screenshots:/root/cypress/screenshots:rw,delegated
      - ./cypress/logs:/root/cypress/logs:rw,delegated
    depends_on:
      - workflow
      - json-server

  go-lint:
    image: golangci/golangci-lint:v2.12.2
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.cache/golangci-lint/v2.2.1:/root/.cache
    command: golangci-lint run -v --timeout 5m

  gosec:
    image: securego/gosec:latest
    working_dir: /app
    volumes:
      - .:/app
    command: -exclude-dir=.gocache -fmt=sarif -out=/app/test-results/gosec.sarif -stdout -verbose=text /app/...

  watch-assets:
    image: node:24-alpine3.23@sha256:595398b0081eacda8e1c4c5b97b76cd1020e4d58a8ebcb4843b9bca1e79e7436
    working_dir: /home/node/app
    entrypoint: ["sh"]
    volumes:
      - ./:/home/node/app
      - watch-assets-node-modules:/home/node/app/node_modules

volumes:
  watch-assets-node-modules:
