version: 2.1

workflows:
  version: 2
  pr:
    jobs:
      - test
      - push:
          requires: [test]

orbs:
  ecr:
    commands:
      login:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
          - run:
              name: Login to ECR
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::311462405659:role/sirius-ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                eval $(aws ecr get-login --no-include-email --region=eu-west-1)
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  test:
    docker:
      - image: circleci/golang
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install modules
          command: go mod download
      - run: mkdir -p /tmp/test-results
      - run:
          name: Run tests
          command: gotestsum --junitfile /tmp/test-results/unit-tests.xml
      - store_test_results:
          path: /tmp/test-results
        - run:
          name: Publish pacts
          command: PACT_CONSUMER_VERSION=$(echo $CIRCLE_SHA1 | cut -c -7) go run internal/pact/publish.go
          environment:
            PACT_DIR: ./pacts
            PACT_BROKER_URL: https://pact-broker.api.opg.service.justice.gov.uk
            PACT_BROKER_USERNAME: admin
            PACT_TAG: v1_production

  push:
    executor: ecr/python
    resource_class: small
    parameters:
      container_repo_url:
        type: string 
        default: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/sirius-workflow
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name: Build
          command: |
            docker build --tag sirius-workflow:latest -f docker/sirius-workflow/Dockerfile .
      - ecr/login
      - run:
          name: Push container
          command: |
            export SHORT_HASH=${CIRCLE_SHA1:0:7} >> $BASH_ENV
            docker tag sirius-workflow:latest << parameters.container_repo_url >>:latest
            docker tag sirius-workflow:latest << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              # We want all of the tags pushed
              docker push << parameters.container_repo_url >>
            else
              docker push << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            fi