version: "3.6"

services:
  workflow:
    build:
      context: ..
      dockerfile: ./docker/sirius-workflow/Dockerfile
    ports: ["8080:8888"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      SHOW_CASELOAD: 1
      SHOW_DEPUTY_TASKS: 1

  puppeteer:
    build: ./puppeteer
    depends_on:
      - workflow
      - json-server
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$CIRCLE_SHA1
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-workflow
      - LHCI_GITHUB_APP_TOKEN

  cypress:
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    command: ["--headless", "-b", "chrome"]
    volumes:
      - ../cypress/screenshots:/root/cypress/screenshots:rw,delegated
      - ../cypress/logs:/root/cypress/logs:rw,delegated
    depends_on:
      - workflow
      - json-server

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'
