version: "3.6"

services:
  workflow:
    build:
      context: ..
      dockerfile: ./docker/sirius-workflow/Dockerfile
    ports: ["8888:1234"]
    environment:
      SIRIUS_URL: http://docker.for.mac.localhost:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080
      PREFIX: /supervision/workflow
      SHOW_CASELOAD: 1
      SHOW_DEPUTY_TASKS: 1
