version: "3.6"
services:
  app:
    build:
      target: dev
    ports:
      - '2345:2345'
    volumes:
      - ..:/app:rw,delegated

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'
