version: "3.6"
services:
  app:
    build:
      target: dev
    ports:
      - '2345:2345'
    volumes:
      - ..:/app:rw,delegated
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'
