version: "3.6"
services:
  workflow:
    build:
      target: dev
    ports:
      - '2345:2345'
    volumes:
      - ..:/app:rw,delegated
      - ../json-server/config:/app/config
      - /app/web/static
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      SHOW_CASELOAD: 1

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'
