version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/sirius-user-management/Dockerfile
    ports: ["8888:8080"]
    environment:
      SIRIUS_URL: http://docker.for.mac.localhost:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080
