version: "3.6"

services:
  workflow:
    image: sirius/sirius-workflow:latest
    build:
      context: ..
      dockerfile: ./docker/sirius-workflow/Dockerfile
    ports: ["8080:8888"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      SHOW_CASELOAD: 1
      SHOW_DEPUTY_TASKS: 1

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'

  test-runner:
    build:
      context: ..
      dockerfile: ./docker/test-runner/Dockerfile
    working_dir: /go/src/app
    volumes:
      - ../:/go/src/app

  cypress:
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    command: ["--headless", "-b", "chrome"]
    volumes:
      - ../cypress/screenshots:/root/cypress/screenshots:rw,delegated
      - ../cypress/logs:/root/cypress/logs:rw,delegated
    depends_on:
      - workflow
      - json-server
  
  go-lint:
    image: golangci/golangci-lint:v1.54.2@sha256:2082f5379c48c46e447bc1b890512f3aa9339db5eeed1a483a34aae9476ba6ee
    working_dir: /go/src/app
    volumes:
      - ../:/go/src/app
      - ../.cache/golangci-lint/v1.53.3:/root/.cache
    command: golangci-lint run -v --timeout 5m
