version: "3.6"
services:
  workflow:
    build:
      target: dev
    ports:
      - '2345:2345'
    volumes:
      - .:/app:rw,delegated
      - ./json-server/config:/app/config
      - /app/web/static

  yarn:
    command: watch
  
  json-server:
    build:
      dockerfile: docker/json-server/Dockerfile
    ports:
      - '3000:3000'
