FROM node:14.13.1-alpine3.11

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN npm i -g pa11y-ci@2.4 @lhci/cli@0.4.x

COPY pa11yci.json .pa11yci
COPY lighthouserc.js .

CMD pa11y-ci
